Completed Loops
Alex-ArceJr/javascript-prep-0223-code-solutions pull request #11
Opened 2023-03-04 22:47 UTC by Alex-ArceJr

<img width="1090" alt="Screen Shot 2023-03-04 at 2 46 54 PM" src="https://user-images.githubusercontent.com/106491940/222932046-17ac0a80-b6f9-4ad8-8433-57ca2d4f7d19.png">

2023-03-04 22:49 UTC, Zhiwutian requested changes
great work! one small update!

2023-03-04 22:49 UTC, Zhiwutian commented on prep-javascript-loops/main.js
> +function forLoop2() {
for this function, you don't want to return an array, although you did that well! You just want to console log the string each time the loop decrements with the new index value.

2023-03-04 22:58 UTC, Alex-ArceJr commented
<img width="330" alt="Screen Shot 2023-03-04 at 2 58 05 PM" src="https://user-images.githubusercontent.com/106491940/222932379-3a551a53-424a-4790-a2d9-87b9e0c99ea7.png">

2023-03-04 22:59 UTC, Alex-ArceJr commented
<img width="445" alt="Screen Shot 2023-03-04 at 2 59 11 PM" src="https://user-images.githubusercontent.com/106491940/222932417-954d7147-c27f-4456-8437-96004ec55b3c.png">

2023-03-06 22:00 UTC, Zhiwutian approved these changes
👍🏼

2023-03-07 05:40 UTC, merged